# HTTP Server Configuration
http:
  port: # Port to listen to.

mqtt:
  url: "mqtt://localhost:1883" # URL of the MQTT broker

# Database Configuration
database:
  host: # Host of the database
  port: # Port of the database
  database: # Database name
  username: # Username to connect to the database
  password: # Password to connect to the database
